### ISSUE TITLE
Suggested changes to the `AesGcmEncryptedBlock` API

### ISSUE THREAD

**Issue by tiesselune** [mozilla/rust-ece#50]
Hi, I've got a new improvement suggestion, this time about the API of the `headers` function in the `AesGcmEncryptedBlock` struct:

https://github.com/mozilla/rust-ece/blob/51e7fb62382ba2360a5c04772428727191e345e8/src/aesgcm.rs#L60-L69

Right now, this function consumes `self` by moving it into the function.

In practice, we want to get both the headers AND the ciphertext preferably without copying them, but as of now the `headers` function consumes `self` by value, creating a "copy or double-move" scenario.

The thing is, nothing is consumed in the `headers` function, making it possible to pass `self` by reference without changing anything else:

```rust
    pub fn headers(&self) -> HashMap<String, String> {
```

Furthermore, the keys are all static, so the hashmap could be changed from a `HashMap<String,String>` to a `HashMap<&'static str,String>`, which would avoid some dynamic allocation (all keys use a `&str` with the call to `to_owned`). Since the draft for this legacy protocol is unlikely to change, there is no  reason for the keys to not be static `str`s, even if I understand why it would have been implemented that way initially.

I see several options here:
 - Changing the API and introducing a breaking change here, since AesGcmEncryptedBlock is exposed to the API (even more now that my previous Pull request is merged)
 - Making another function (`generate_headers`) that does essentially the same thing with an optimized API (passing self by reference and outputing `&'static str` keys) and deprecate the previous one
 - Going even a bit further by writing a new function that takes another argument in the form of an `Option<String>` to provide VAPID ecdsa part of the `Crypto-Key` (to avoid having to merge it later) and return a `Vec<(&'static str, String)>`, to avoid the HashMap altogether and save a few CPU operations.

I think I could tackle that so let me know if you think any of this is a good idea.

**Comment by rfk** [comment]
> In practice, we want to get both the headers AND the ciphertext preferably without copying them, 
> but as of now the headers function consumes self by value, creating a "copy or double-move" scenario.

Good point. I don't know the historical reasons why the API might be shaped this way, but I can't think of any good reason for it.

> The thing is, nothing is consumed in the headers function, making it possible to pass self by reference without
> changing anything else:

This change sounds reasonable to me.

> Changing the API and introducing a breaking change here, since AesGcmEncryptedBlock is exposed to the API
> (even more now that my previous Pull request is merged)

This sounds like the simplest option. According to crates.io this crate currently has [zero public dependents](https://crates.io/crates/ece/reverse_dependencies) and the places we use it internally don't seem to call this method. So, I think going ahead with a breaking API change here sounds fine 👍.

(Which, if we're going to make a breaking change anyway, may be a good opportunity to look at hiding some of the currently-public things that don't seem like they need to be public).

**Comment by tiesselune** [comment]
I have just submitted a pull request (#51) with the version I had in mind. 

Please tell me if you think it's OK and if you need me to add some form of testing.

**Comment by rfk** [comment]
This was resolved by the above PR; thanks @tiesselune!
